#ddev-generated
# Simple template to demonstrate ddev-addon-wordpress-bedrock-sage
services:
  ddev-addon-wordpress-bedrock-sage:
    container_name: ddev-${DDEV_SITENAME}-ddev-addon-wordpress-bedrock-sage
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
